# Arquivo .yml de exemplo de onde deve colocar as credenciais
# Example .yml file of where to place the credentials
server:
  port: 8081
  address: 0.0.0.0

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/dbteste}
    username: ${DB_USER:usuarioteste}
    password: ${DB_PASS:senhateste}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    issuer: phoenix-api
    secret: ${JWT_SECRET:changeme-very-secret-key-at-least-32-chars}
    expirationMinutes: 60

logging:
  level:
    org.springframework.security: DEBUG
